Implementation of project features
YuvrajM108/carbon-intensity-app-capstone pull request #2
Opened 2021-10-16 14:47 UTC by YuvrajM108

In this pull request, I did the following:

- Selected an API to fetch data from.
- Created components for the application and added routes for navigating to the components.
- Created a store for the application.
- Created actions and action creators for fetching data from the API.
- Created reducers for each component and combined the reducers in the store.
- Connected actions and reducers to the components and outputted data from the store to the components.
- Styled the components according to the given design.
- Created unit and integration tests.

2021-10-16 20:41 UTC, henatan99 requested changes
Hi @YuvrajM108 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [ ] I could not find a video link either in your PR summary or in the readme. The project requires you once you have finished the development of the project, you should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:
  - a description of the project.
  - a demo of the project features.
  - you should also highlight some interesting piece of code or something you built that you are very proud of.


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-16 20:41 UTC, henatan99 commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] Kindly add an "Acknowledgements" section or similar that gives appropriate credit to Nelson Sakwa the author of the original design, as required by the Creative Commons License. :pray:

2021-10-16 20:41 UTC, henatan99 commented on src/__mocks__/mockAPIRequest.js
> +};
- [ ] OPTIONAL: I think you could have made just a single request with the URL `https://api.carbonintensity.org.uk/regional/regionid/` and filter with region_id for a particular region. :pray:

2021-10-16 20:41 UTC, henatan99 commented on src/App.css
> +a.nav-link {
- [ ] While you are free to pick a base color of your own it is a requirement to maintain layout: composition and space between elements of the original design. Kindly compare the layout for this element in the original design and make changes to your design to match it. 

![image](https://user-images.githubusercontent.com/64894927/137601554-5b22a62b-ecf1-4777-bb8d-9e59f871cee4.png)
![image](https://user-images.githubusercontent.com/64894927/137601572-d25e8e81-b881-46a1-8812-42d2c682e7c9.png)

2021-10-17 04:45 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-10-17 04:46 UTC, merged